# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d13605f2c64b22f491ee4ec4d5604978028bd24c63942ed1ea0e0731347f5d26b5fdeabd7e5505901d400333e057404452c206bb8218752b71ee714aac467314

test:
  secret_key_base: 6889c3fcd90e663d6bc4a1c2d6bf55d609b3a88d655c95a58759b3b570a1c0406e7fd372989697eb6513b349922914dc36d8a534768a7591b29a65de2905a295

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
